name: Fake Contributions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate fake commits
        run: |
          for i in {1..5}
          do
            echo "$(date) $i $RANDOM" >> fake.txt
            git add fake.txt
            git commit -m "Fake commit $i on $(date)"
          done

      - name: Push commits
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          git config user.name "Abdul Alameda"
          git config user.email "abduldev.muhammad3589@gmail.com"
          git remote set-url origin "https://x-access-token:${TOKEN}@github.com/${REPO}"
          git push origin HEAD:main
